version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@3.0
jobs:
  test_my_api:
    executor: aws-serverless/default
    steps:
      - run: echo "Run your tests here"
workflows:
  test_and_deploy:
    jobs:
      - aws-serverless/deploy:
          name: deploy-staging
          stack-name: staging-stack
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-cu9oyxmbebq7
          template: template.yml
      - test_my_api:
          requires:
            - deploy-staging
      - aws-serverless/deploy:
          name: deploy-production
          requires:
            - test_my_api
          stack-name: production-stack
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-cu9oyxmbebq7
          template: template.yml
